apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-newsletter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek-newsletter
  template:
    metadata:
      labels:
        app: deepseek-newsletter
    spec:
      containers:
      - name: deepseek-newsletter
        image: localhost:32000/deepseek-newsletter:latest
        env:
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: deepseek-secrets
              key: DEEPSEEK_API_KEY
        - name: EMAILS_JSON
          valueFrom:
            secretKeyRef:
              name: deepseek-secrets
              key: EMAILS_JSON
        - name: PROMPTS_JSON
          valueFrom:
            secretKeyRef:
              name: deepseek-secrets
              key: PROMPTS_JSON
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "print('ready')"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "print('alive')"
